# Generated by Django 5.2.17 on 2026-09-23 09:30

import django.db.models.deletion
import posts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(help_text="Stable identifier used in code, e.g. 'linkedin'", unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Optional internal title — not necessarily published to the platform', max_length=500)),
                ('content_plain', models.TextField(help_text='Main plain-text content')),
                ('content_html', models.TextField(blank=True, default='', help_text='Optional HTML representation where the platform supports it')),
                ('hashtags', models.TextField(blank=True, default='', help_text="Common hashtags, e.g. '#AI #Python #Django'")),
                ('created_by_type', models.CharField(choices=[('user', 'User'), ('ai_system', 'AI System')], default='user', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('partially_published', 'Partially Published'), ('failed', 'Failed')], db_index=True, default='draft', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Human author; NULL for AI-created posts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('mime_type', models.CharField(blank=True, default='', help_text='e.g. image/jpeg', max_length=100)),
                ('file', models.FileField(upload_to=posts.models._post_media_upload_path)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Controls display/publishing order; lower = first')),
                ('is_main', models.BooleanField(default=False, help_text='Main/thumbnail image for this post')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='posts.post')),
            ],
            options={
                'verbose_name': 'Post Media',
                'verbose_name_plural': 'Post Media',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PostTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('retrying', 'Retrying'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Target-specific schedule; NULL = publish immediately when triggered', null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('external_post_id', models.CharField(blank=True, default='', max_length=500)),
                ('external_post_url', models.URLField(blank=True, default='', max_length=1000)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='', help_text='Most recent sanitized failure reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='posts.post')),
            ],
            options={
                'verbose_name': 'Post Target',
                'verbose_name_plural': 'Post Targets',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostTargetContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('content_plain', models.TextField(blank=True, default='')),
                ('content_html', models.TextField(blank=True, default='')),
                ('hashtags', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_override', to='posts.posttarget')),
            ],
            options={
                'verbose_name': 'Post Target Content',
                'verbose_name_plural': 'Post Target Contents',
            },
        ),
        migrations.CreateModel(
            name='PublishingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('response_type', models.CharField(blank=True, default='', help_text='e.g. HTTP_200, HTTP_429, TIMEOUT, API_ERROR', max_length=100)),
                ('response_message', models.TextField(blank=True, default='', help_text='Sanitized platform response / error message — never include tokens')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='posts.posttarget')),
            ],
            options={
                'verbose_name': 'Publishing Log',
                'verbose_name_plural': 'Publishing Logs',
                'ordering': ['post_target', 'attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_label', models.CharField(help_text="User-friendly label, e.g. 'My Main LinkedIn'", max_length=200)),
                ('external_account_id', models.CharField(blank=True, default='', help_text="Platform's own ID for this account/page/channel", max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_accounts', to='posts.platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'ordering': ['platform__name', 'account_label'],
            },
        ),
        migrations.AddField(
            model_name='posttarget',
            name='social_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_targets', to='posts.socialaccount'),
        ),
        migrations.CreateModel(
            name='SocialAccountCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('access_token', models.TextField(help_text='OAuth access token — never expose in UI or logs')),
                ('refresh_token', models.TextField(blank=True, default='', help_text='OAuth refresh token where applicable')),
                ('scope', models.TextField(blank=True, default='', help_text='Granted OAuth scopes')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Token expiry — null means no known expiry', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='posts.socialaccount')),
            ],
            options={
                'verbose_name': 'Social Account Credential',
                'verbose_name_plural': 'Social Account Credentials',
            },
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('external_account_id', ''), _negated=True), fields=('user', 'platform', 'external_account_id'), name='unique_user_platform_external_account'),
        ),
        migrations.AddConstraint(
            model_name='posttarget',
            constraint=models.UniqueConstraint(fields=('post', 'social_account'), name='unique_post_social_account'),
        ),
    ]
