# Generated by Django 5.2.17 on 2026-09-23 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='socialaccount',
            name='unique_user_platform_external_account',
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['user', 'platform'], name='idx_soc_acc_user_platform'),
        ),
    ]
