# Generated by Django 5.2.17 on 2026-09-23 11:27

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_oauthstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishinglog',
            name='request_id',
            field=models.CharField(blank=True, default='', help_text='Unique request identifier for idempotency tracking', max_length=64),
        ),
        migrations.AddField(
            model_name='socialaccountcredential',
            name='last_refresh_at',
            field=models.DateTimeField(blank=True, help_text='Last time token was successfully refreshed', null=True),
        ),
        migrations.AlterField(
            model_name='socialaccountcredential',
            name='access_token',
            field=encrypted_model_fields.fields.EncryptedTextField(help_text='OAuth access token — encrypted at rest, never expose in UI or logs'),
        ),
        migrations.AlterField(
            model_name='socialaccountcredential',
            name='refresh_token',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, default='', help_text='OAuth refresh token where applicable — encrypted at rest'),
        ),
        migrations.AddIndex(
            model_name='publishinglog',
            index=models.Index(fields=['request_id'], name='idx_pub_log_request_id'),
        ),
    ]
