# Generated by Django 5.2.17 on 2026-09-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_phase5_7_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='image', max_length=20),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='mime_type',
            field=models.CharField(blank=True, default='', help_text='e.g. image/jpeg, application/pdf', max_length=100),
        ),
    ]
