"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.
Upgraded to Django 5.2.17 for Python 3.14 compatibility.

For the full settings reference see:
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# Environment helpers
# ---------------------------------------------------------------------------
# Values are read from the process environment (or from a .env file loaded
# by your shell / a tool such as python-dotenv added later).

def _env(key: str, default: str = "") -> str:
    return os.environ.get(key, default).strip()


# ---------------------------------------------------------------------------
# Security
# ---------------------------------------------------------------------------

SECRET_KEY = _env(
    "DJANGO_SECRET_KEY",
    # Fallback is fine for local dev only — never leave this in production.
    "django-insecure-local-dev-secret-key-replace-in-production",
)

DEBUG = _env("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    h.strip()
    for h in _env("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if h.strip()
]

# Trust ngrok and any other proxy domains for CSRF
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in _env("CSRF_TRUSTED_ORIGINS", "http://127.0.0.1:8000,http://localhost:8000").split(",")
    if o.strip()
]


# ---------------------------------------------------------------------------
# Application definition
# ---------------------------------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "django_q",
    "encrypted_model_fields",
    # Local apps
    "core",
    "rbac",
    "posts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Project-level templates directory (create templates/ when needed)
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # RBAC stats available to all templates
                "rbac.context_processors.rbac_stats",
                # Posts module stats
                "posts.context_processors.posts_stats",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------
# Reads connection details from environment variables.
# When DB_ENGINE is not set, falls back to SQLite (handy for CI / quick tests).
#
# MySQL example (.env):
#   DB_ENGINE=django.db.backends.mysql
#   DB_NAME=tool
#   DB_USER=root
#   DB_PASSWORD=
#   DB_HOST=localhost
#   DB_PORT=3306

_db_engine = _env("DB_ENGINE")

if _db_engine:
    _db_options = {}
    if "mysql" in _db_engine:
        # Enable Strict Mode — prevents silent data truncation/corruption
        _db_options = {
            "OPTIONS": {"init_command": "SET sql_mode='STRICT_TRANS_TABLES'"}
        }

    DATABASES = {
        "default": {
            "ENGINE":   _db_engine,
            "NAME":     _env("DB_NAME"),
            "USER":     _env("DB_USER"),
            "PASSWORD": _env("DB_PASSWORD"),
            "HOST":     _env("DB_HOST", "localhost"),
            "PORT":     _env("DB_PORT", "3306"),
            **_db_options,
        }
    }
else:
    # Fallback: SQLite — zero-config for local hacking / running tests
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# ---------------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ---------------------------------------------------------------------------
# Internationalisation
# ---------------------------------------------------------------------------

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ---------------------------------------------------------------------------
# Static files
# ---------------------------------------------------------------------------

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]   # project-level static assets
STATIC_ROOT = BASE_DIR / "staticfiles"     # collected by `collectstatic`

# ---------------------------------------------------------------------------
# Media files (user-uploaded content)
# ---------------------------------------------------------------------------

MEDIA_URL  = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ---------------------------------------------------------------------------
# Default primary key
# ---------------------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ---------------------------------------------------------------------------
# Authentication
# ---------------------------------------------------------------------------

LOGIN_URL = "core:login"                 # where @login_required redirects to
LOGIN_REDIRECT_URL = "core:dashboard"    # after a successful login
LOGOUT_REDIRECT_URL = "core:login"       # after logout


# ---------------------------------------------------------------------------
# LinkedIn OAuth
# ---------------------------------------------------------------------------
# Credentials come from .env — never hard-code them here.
#
# Callback URL (register this EXACTLY in your LinkedIn App settings):
#   Local dev:   http://127.0.0.1:8000/posts/social-accounts/linkedin/callback/
#   Production:  https://yourdomain.com/posts/social-accounts/linkedin/callback/

LINKEDIN_CLIENT_ID     = _env("LINKEDIN_CLIENT_ID")
LINKEDIN_CLIENT_SECRET = _env("LINKEDIN_CLIENT_SECRET")

# Override this in .env for production — Django auto-builds it from request
# if left blank, but setting it explicitly avoids issues behind proxies.
LINKEDIN_REDIRECT_URI  = _env("LINKEDIN_REDIRECT_URI", "")

# Scopes needed:
#   openid, profile, email  — to read the user's LinkedIn identity
#   w_member_social          — to create posts on the member's feed
LINKEDIN_SCOPES = "openid profile email w_member_social"

# OAuthState records older than this are considered expired and will be
# rejected on callback + cleaned up periodically.
OAUTH_STATE_EXPIRY_MINUTES = 10


# ---------------------------------------------------------------------------
# LinkedIn Page OAuth  (separate app — requires Marketing Developer Platform)
# ---------------------------------------------------------------------------
# Callback URL (register this EXACTLY in your LinkedIn Page App):
#   Local dev:   http://127.0.0.1:8000/posts/social-accounts/linkedin-page/callback/
#   Production:  https://yourdomain.com/posts/social-accounts/linkedin-page/callback/
#
# Required Products in this app:
#   Marketing Developer Platform → grants r_organization_social + w_organization_social

LINKEDIN_PAGE_CLIENT_ID     = _env("LINKEDIN_PAGE_CLIENT_ID")
LINKEDIN_PAGE_CLIENT_SECRET = _env("LINKEDIN_PAGE_CLIENT_SECRET")
LINKEDIN_PAGE_REDIRECT_URI  = _env("LINKEDIN_PAGE_REDIRECT_URI", "")
LINKEDIN_PAGE_SCOPES        = "r_basicprofile r_organization_social w_organization_social"


# ---------------------------------------------------------------------------
# Logging — print Django and app logs to the console
# ---------------------------------------------------------------------------

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "posts": {
            "handlers": ["console"],
            "level":    "DEBUG",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level":    "DEBUG",
            "propagate": False,
        },
    },
}


# ---------------------------------------------------------------------------
# Facebook OAuth
# ---------------------------------------------------------------------------
# Credentials come from .env — never hard-code them here.
#
# Callback URL (register this EXACTLY in Facebook App → Facebook Login → Settings):
#   Local dev:   http://127.0.0.1:8000/posts/social-accounts/facebook/callback/
#   Production:  https://yourdomain.com/posts/social-accounts/facebook/callback/
#
# Required permissions: public_profile, pages_show_list, pages_manage_posts

FACEBOOK_APP_ID     = _env("FACEBOOK_APP_ID")
FACEBOOK_APP_SECRET = _env("FACEBOOK_APP_SECRET")

# Override in .env for production / proxies; Django auto-builds it if blank.
FACEBOOK_REDIRECT_URI = _env("FACEBOOK_REDIRECT_URI", "")

# Scopes requested during OAuth. Keep in sync with your app's approved permissions.
FACEBOOK_SCOPES = "public_profile,pages_show_list,pages_manage_posts"


# ---------------------------------------------------------------------------
# Instagram OAuth  (uses the same Facebook App — separate redirect URI)
# ---------------------------------------------------------------------------
# Callback URL (add to Facebook App → Facebook Login → Valid OAuth Redirect URIs):
#   Local dev:   http://127.0.0.1:8000/posts/social-accounts/instagram/callback/
#   Ngrok:       https://follow-macaroni-handiwork.ngrok-free.dev/posts/social-accounts/instagram/callback/
#   Production:  https://yourdomain.com/posts/social-accounts/instagram/callback/
#
# Required permissions (Meta App → Permissions and Features):
#   instagram_basic, instagram_content_publish,
#   pages_read_engagement, business_management, pages_show_list

INSTAGRAM_REDIRECT_URI = _env("INSTAGRAM_REDIRECT_URI", "")
INSTAGRAM_SCOPES = (
    "instagram_basic,instagram_content_publish,"
    "pages_read_engagement,business_management,pages_show_list"
)
INSTAGRAM_APP_ID     = _env("INSTAGRAM_APP_ID")
INSTAGRAM_APP_SECRET = _env("INSTAGRAM_APP_SECRET")
INSTAGRAM_PUBLIC_BASE_URL = _env("INSTAGRAM_PUBLIC_BASE_URL", "")


# ---------------------------------------------------------------------------
# Django-Q Task Queue
# ---------------------------------------------------------------------------
# Asynchronous task processing for publishing and scheduling.
# Uses Django ORM backend — zero additional dependencies.
#
# Start worker:  python manage.py qcluster
# Monitor:       python manage.py qmonitor

Q_CLUSTER = {
    "name":          "SocialPublishing",
    "workers":       4,              # concurrent workers
    "timeout":       90,             # task timeout in seconds
    "retry":         120,            # retry failed tasks after 2 minutes
    "queue_limit":   50,             # max tasks in queue
    "bulk":          10,             # messages per batch
    "orm":           "default",      # use Django ORM as broker
    "poll":          1,              # polling interval in seconds
    "catch_up":      False,          # don't execute missed schedules
    "save_limit":    100,            # keep last 100 successful tasks
    "sync":          DEBUG,          # run synchronously in DEBUG mode for testing
    "ack_failures":  True,           # acknowledge failed tasks
}


# ---------------------------------------------------------------------------
# Encryption Key for Credentials
# ---------------------------------------------------------------------------
# CRITICAL: Generate a secure key and store in .env:
#   from cryptography.fernet import Fernet
#   print(Fernet.generate_key().decode())
#
# Never commit this key to version control!

FIELD_ENCRYPTION_KEY = _env(
    "FIELD_ENCRYPTION_KEY",
    "",  # MUST be set in production
).strip()
